---
# Playbook that installs and configures picoCTF-web servers

- import_tasks: dependencies.yml
  tags:
    - network
    - dependency

- import_tasks: nodejs.yml
  tags:
    - network
    - dependency

- import_tasks: nginx.yml

- import_tasks: picoCTF-webapp.yml
  tags:
    - devploy

- import_tasks: gunicorn.yml

- import_tasks: daemons.yml

- import_tasks: auto_configure.yml

- name: Ensure nginx is running
  service:
    name: nginx
    state: started
    enabled: yes
