---
# Playbook that installs MongoDB and associated utilities
# TODO: Consolidate mongodb tasks into web


- name: Add apt key by id
  shell: "curl -fsSL https://www.mongodb.org/static/pgp/server-7.0.asc | gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg --dearmor"
  become: yes
  ignore_errors : true

- name: Add apt source by id
  shell: 'echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-7.0.list'
  become: yes


#- name: Add apt key by id
#  apt_key:
#    keyserver: "{{mongodb_apt_keyserver}}"
#    id: "{{mongodb_apt_key_id}}"

#- name: Add repository
#  apt_repository:
#    repo: "{{ mongodb_repo }}"
#    state: present

- name: Update apt
  apt:
    update_cache: yes

- name: Install mongo
  apt:
    allow_unauthenticated: true
    name: ['mongodb-org']  # from PPA
    state: present

- name: Ensure mongodb is running
  service:
    name: "{{ mongodb_daemon_name }}"
    state: started
    enabled: yes
