---
# Playbook that installs and configures picoCTF-shell servers

# Needed so picoCTF-web can log in to get deployment information
- name: Set password for admin user
  user:
    name: "{{ ansible_user }}"
    password: "{{ shell_admin_password_crypt }}"
  no_log: True

- import_tasks: dependencies.yml
  tags:
    - network
    - dependency

- import_tasks: shell_manager.yml

- import_tasks: nginx.yml

- import_tasks: pam_and_services.yml

- import_tasks: deploy_problems.yml

- name: Ensure nginx is running
  service:
    name: nginx
    state: started
    enabled: yes

- name: Copy over 99-motd
  copy:
    src: 99-motd
    dest: /etc/update-motd.d/99-motd
    owner: root
    group: root
    mode: 0755

# Missing
# journald
# services
#   sudo systemctl add-wants default.target shell_manager.target
# hardening
